import { PDFDocument, StandardFonts, rgb, PDFPage, PDFFont } from "pdf-lib";

interface PDFOptions {
  title: string;
  content: string;
  subtitle?: string;
}

export async function generatePDF(options: PDFOptions): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.TimesRoman);
  const fontBold = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);

  const pageWidth = 595.28; // A4
  const pageHeight = 841.89;
  const margin = 50;
  const lineHeight = 14;
  const titleSize = 16;
  const subtitleSize = 11;
  const contentSize = 10;

  let page = pdfDoc.addPage([pageWidth, pageHeight]);
  let yPos = pageHeight - margin;

  // Title
  page.drawText(options.title, {
    x: margin,
    y: yPos,
    size: titleSize,
    font: fontBold,
    color: rgb(0, 0, 0),
  });
  yPos -= titleSize + 8;

  // Subtitle / date
  if (options.subtitle) {
    page.drawText(options.subtitle, {
      x: margin,
      y: yPos,
      size: subtitleSize,
      font: font,
      color: rgb(0.4, 0.4, 0.4),
    });
    yPos -= subtitleSize + 4;
  }

  // Horizontal line
  page.drawLine({
    start: { x: margin, y: yPos },
    end: { x: pageWidth - margin, y: yPos },
    thickness: 0.5,
    color: rgb(0.7, 0.7, 0.7),
  });
  yPos -= 20;

  // Content - wrap text
  const maxWidth = pageWidth - 2 * margin;
  const lines = wrapText(options.content, font, contentSize, maxWidth);

  for (const line of lines) {
    if (yPos < margin + lineHeight) {
      // New page
      page = pdfDoc.addPage([pageWidth, pageHeight]);
      yPos = pageHeight - margin;
    }

    // Handle bold lines (lines that look like headings)
    const isBold = line.trim().match(/^[A-Z\s:]+$/) || line.trim().startsWith("AFFIDAVIT") || line.trim().startsWith("CERTIFICATE");

    page.drawText(line, {
      x: margin,
      y: yPos,
      size: contentSize,
      font: isBold ? fontBold : font,
      color: rgb(0, 0, 0),
    });
    yPos -= lineHeight;
  }

  // Footer on each page
  const pages = pdfDoc.getPages();
  pages.forEach((p, idx) => {
    p.drawText(`Page ${idx + 1} of ${pages.length}`, {
      x: pageWidth / 2 - 30,
      y: 30,
      size: 8,
      font: font,
      color: rgb(0.5, 0.5, 0.5),
    });
    p.drawText("Generated by DSRT CEOS", {
      x: margin,
      y: 30,
      size: 8,
      font: font,
      color: rgb(0.5, 0.5, 0.5),
    });
    const dateStr = new Date().toLocaleDateString("en-IN");
    p.drawText(dateStr, {
      x: pageWidth - margin - 50,
      y: 30,
      size: 8,
      font: font,
      color: rgb(0.5, 0.5, 0.5),
    });
  });

  return pdfDoc.save();
}

function wrapText(text: string, font: PDFFont, fontSize: number, maxWidth: number): string[] {
  const lines: string[] = [];
  const paragraphs = text.split("\n");

  for (const paragraph of paragraphs) {
    if (paragraph.trim() === "") {
      lines.push("");
      continue;
    }

    const words = paragraph.split(" ");
    let currentLine = "";

    for (const word of words) {
      const testLine = currentLine ? currentLine + " " + word : word;
      // Sanitize: remove non-ASCII chars that StandardFonts can't render
      const sanitized = testLine.replace(/[^\x20-\x7E]/g, "");
      try {
        const width = font.widthOfTextAtSize(sanitized, fontSize);
        if (width > maxWidth && currentLine) {
          lines.push(currentLine.replace(/[^\x20-\x7E]/g, ""));
          currentLine = word;
        } else {
          currentLine = testLine;
        }
      } catch {
        lines.push(currentLine.replace(/[^\x20-\x7E]/g, ""));
        currentLine = word;
      }
    }

    if (currentLine) {
      lines.push(currentLine.replace(/[^\x20-\x7E]/g, ""));
    }
  }

  return lines;
}

export async function generateChecklistPDF(checklist: any): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.TimesRoman);
  const fontBold = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);

  const page = pdfDoc.addPage([595.28, 841.89]);
  const margin = 50;
  let yPos = 800;

  // Title
  page.drawText("DOCUMENT SUBMISSION CHECKLIST", {
    x: margin, y: yPos, size: 16, font: fontBold,
  });
  yPos -= 20;

  page.drawText(`Tender Reference: ${(checklist.tenderRef || "").substring(0, 80)}`, {
    x: margin, y: yPos, size: 10, font,
  });
  yPos -= 14;

  page.drawText(`Company: ${checklist.companyName || ""}`, {
    x: margin, y: yPos, size: 10, font,
  });
  yPos -= 25;

  // Table headers
  page.drawLine({ start: { x: margin, y: yPos + 5 }, end: { x: 545, y: yPos + 5 }, thickness: 0.5 });
  yPos -= 5;
  page.drawText("S.No", { x: margin, y: yPos, size: 10, font: fontBold });
  page.drawText("Document", { x: margin + 50, y: yPos, size: 10, font: fontBold });
  page.drawText("Status", { x: 400, y: yPos, size: 10, font: fontBold });
  page.drawText("Page", { x: 490, y: yPos, size: 10, font: fontBold });
  yPos -= 5;
  page.drawLine({ start: { x: margin, y: yPos }, end: { x: 545, y: yPos }, thickness: 0.5 });
  yPos -= 15;

  // Items
  for (const item of checklist.items) {
    if (yPos < 60) break;
    const docName = String(item.document).substring(0, 50).replace(/[^\x20-\x7E]/g, "");
    page.drawText(String(item.slNo), { x: margin, y: yPos, size: 10, font });
    page.drawText(docName, { x: margin + 50, y: yPos, size: 10, font });
    // Checkbox
    page.drawRectangle({ x: 405, y: yPos - 2, width: 10, height: 10, borderColor: rgb(0, 0, 0), borderWidth: 1 });
    page.drawText("____", { x: 490, y: yPos, size: 10, font });
    yPos -= 18;
  }

  page.drawText("Generated by DSRT CEOS", { x: margin, y: 30, size: 8, font });
  return pdfDoc.save();
}